---
- name: Playbook for check variables
  hosts: deb11test
  gather_facts: 'yes'
  become: 'yes'
  tasks:
  - name: Print variables
    debug:
       msg: 
         - '{{ ansible_hostname }}'
         - '{{ ansible_fqdn }}'
         - '{{ inventory_hostname }}'
         - '{{ ansible_vars1 }}'
         - '{{ ansible_vars2 }}'
         - '{{ ansible_vars3 }}'
### debugs - chek var
